### ISSUE TITLE
[PROPOSAL] What is MEV(Maximum Extractable Value) and how does it work

### ISSUE THREAD

**Issue by therevealer** [chainstack/developer-hub-content#18]
- Content is:
  [ ] Coding tutorial
  [x] Informational content
  [ ] Other (describe)

- Which blockchain protocol is this about?:
Ethereum

- Description (two or three phrases describing what is it about):
MEV is the maximum value that can be extracted from a block by removing, adding or reordering transactions during block production. In order words, because miners have the ability to decide the order of transactions in a block, they can use it to their own advantage. This is considered one of the biggest threats to Ethereum and other smart-contract-based blockchains.
- Have you published articles in a blog before? If so, please include some links below 👇
https://therevealer.hashnode.dev/how-to-solve-coding-problems-like-a-pro
https://therevealer.hashnode.dev/the-blockchain-trilemma

## Proposed Outline

- Introduction(The impact of the blockchain and how the MEV comes in).
- What is MEV(Definition and how it works in the blockchain)?
- How do miners Extract value? (Practical examples of how miners extract value from blocks).
- Practical Examples of MEV.
- Potential solutions to MEV.
- Conclusion
- Resources

**Comment by Genesis3800** [comment]
Hey @therevealer , thank you for creating a proposal. Your proposal was neat and concise, even if we ignore the merits of your proposed topic. Love to see that.

With regards to the article, Here's a few things we would like to see-

1. A focus on MEV and why it is necessary to incentivize miners/validators?
2. An explanation of how the concept of MEV changes between blockchains like Ethereum and Polygon, since they use different consensus mechanisms as of now.
3. Since the merge is imminent, we would love to see a section that explains how the specifications of MEV will change in Ethereum after the transition.

Please feel free to get back to me with any doubts/concerns you may have. We will try our best to help you finish this article.
Looking forward to hearing from you.

**Comment by therevealer** [comment]
Hey @Genesis3800, thanks for the review.

I'll have no trouble implementing the `2nd` and `3rd` suggestions in the article.

But for the `1st` one, I have some concerns.
Since the MEV talks about how miners/validators extract value for themselves don't you think it would be more appropriate if I talk about how miners/validators are incentivized instead?

**Comment by Genesis3800** [comment]
Actually, that's exactly what I meant by the first point. I should have worded it more clearly. 
I think we're good to go. 
Please confirm to me that you're getting started. I will change the label accordingly.

**Comment by Genesis3800** [comment]
Great!
Best of luck, we'll be looking forward to your first draft.

**Comment by therevealer** [comment]
@Genesis3800 Am done with the draft!
